CREATE CONSTRAINT ON (u:User) ASSERT u.userId IS UNIQUE;
CREATE CONSTRAINT ON (m:Movie) ASSERT m.movieId IS UNIQUE;
CREATE CONSTRAINT ON (g:Genre) ASSERT g.name IS UNIQUE; 
CREATE CONSTRAINT ON (a:Actor) ASSERT a.actorId IS UNIQUE;
CREATE CONSTRAINT ON (d:Director) ASSERT d.directorId IS UNIQUE;

CREATE CONSTRAINT ON (g:Genre) ASSERT g.name IS UNIQUE;
